#!/bin/sh

bat=/sys/class/power_supply/BAT0/
ic=

if [ ! -f "$bat" ]; then
    exit
fi

per="$(cat "$bat/capacity")"

icon() {

if [ "$(cat $bat/status)" = Charging ]; then 
    ic=""
    return
fi

if [ "$per" -gt "90" ]; then
	ic=""
elif [ "$per" -gt "80" ]; then
	ic=""
elif [ "$per" -gt "70" ]; then
	ic=""
elif [ "$per" -gt "60" ]; then
	ic=""
elif [ "$per" -gt "50" ]; then
	ic=""
elif [ "$per" -gt "40" ]; then
	ic=""
elif [ "$per" -gt "30" ]; then
	ic=""
elif [ "$per" -gt "20" ]; then
	ic=""
elif [ "$per" -gt "10" ]; then
	ic=""
	notify-send -u critical "Battery Low" "Connect Charger"
elif [ "$per" -gt "0" ]; then
	ic=""
	notify-send -u critical "Battery Low" "Connect Charger"
fi

}

module() {
#output eww widget
echo "(box :orientation \"v\" :space-evenly \"false\" \
        (button	:class \"bat\" \
			    :tooltip \"Battery: $per%\" \"$ic\"))"
}


icon
module
exit
