#!/bin/sh


symbol() {
if [ $(cat /sys/class/net/w*/operstate) = up ]
then
echo 
elif [ $(cat /sys/class/net/w*/operstate) = down ]
then
echo 
fi
}

name() {
if [ $(cat /sys/class/net/w*/operstate) = up ]; then
wpa_cli status  | grep '^ssid' | sed 's/ssid=/Connected\ to\ /g'
else
echo "Not connected"
fi
}

[ "$1" = "icon" ] && symbol && exit
[ "$1" = "name" ] && name && exit
