#!/bin/sh

ic=(0          )

update(){
ic=(0          )

which_workspaces=$(hyprctl workspaces -j | jq .[].id | sort -n)
current_workspace=$(hyprctl activeworkspace -j | jq .id)

for num in $which_workspaces; do
  ic[$num]=""
done

for i in "${!ic[@]}"; do
  unset -v o"$i"
done

export f"$current_workspace"="$current_workspace"
export o"$current_workspace"="$current_workspace"

}

module() {
#output eww widget
echo 	"(eventbox :onscroll \"echo {} | sed -e 's/up/-1/g' -e 's/down/+1/g' | xargs hyprctl dispatch workspace\" \
          (box	:class \"works\"	:orientation \"$BAR_ORIENTATION\" :spacing 0 :space-evenly \"false\" :valign \"center\"	\
              (eventbox :cursor \"pointer\" (button :onclick \"hyprctl dispatch workspace 1\" :class \"ws-btn\" (label :class \"ws-icon a0$o1$f1\" :text \"${ic[1]}\"))) \
              (eventbox :cursor \"pointer\" (button :onclick \"hyprctl dispatch workspace 2\" :class \"ws-btn\" (label :class \"ws-icon a0$o2$f2\" :text \"${ic[2]}\"))) \
              (eventbox :cursor \"pointer\" (button :onclick \"hyprctl dispatch workspace 3\" :class \"ws-btn\" (label :class \"ws-icon a0$o3$f3\" :text \"${ic[3]}\"))) \
              (eventbox :cursor \"pointer\" (button :onclick \"hyprctl dispatch workspace 4\" :class \"ws-btn\" (label :class \"ws-icon a0$o4$f4\" :text \"${ic[4]}\"))) \
              (eventbox :cursor \"pointer\" (button :onclick \"hyprctl dispatch workspace 5\" :class \"ws-btn\" (label :class \"ws-icon a0$o5$f5\" :text \"${ic[5]}\"))) \
              (eventbox :cursor \"pointer\" (button :onclick \"hyprctl dispatch workspace 6\" :class \"ws-btn\" (label :class \"ws-icon a0$o6$f6\" :text \"${ic[6]}\"))) \
              (eventbox :cursor \"pointer\" (button :onclick \"hyprctl dispatch workspace 7\" :class \"ws-btn\" (label :class \"ws-icon a0$o7$f7\" :text \"${ic[7]}\"))) \
              (eventbox :cursor \"pointer\" (button :onclick \"hyprctl dispatch workspace 8\" :class \"ws-btn\" (label :class \"ws-icon a0$o8$f8\" :text \"${ic[8]}\"))) \
              (eventbox :cursor \"pointer\" (button :onclick \"hyprctl dispatch workspace 9\" :class \"ws-btn\" (label :class \"ws-icon a0$o9$f9\" :text \"${ic[9]}\"))) \
              (eventbox :cursor \"pointer\" (button :onclick \"hyprctl dispatch workspace 10\" :class \"ws-btn\" (label :class \"ws-icon a0$o10$f10\" :text \"${ic[10]}\"))) \
          )\
        )"
}

module

socat -u UNIX-CONNECT:"$XDG_RUNTIME_DIR"/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r event; do 
update
module
done
