# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
#add_newline = true

# Use custom format

#[kubernetes]
#format = 'on [⛵ $context \($namespace\)](dimmed green) '
#disabled = false

palette = "catppuccin_mocha"

format = """
[╭─](fg:sapphire)\
[](bg:crust fg:sapphire)\
$directory\
[](fg:crust bg:sapphire)\
$git_branch\
$git_status\
[](fg:sapphire bg:crust)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$rust\
[](fg:crust bg:sapphire)\
$kubernetes\
$docker_context\
[](fg:sapphire bg:crust)\
$time(fg:sapphire)\
[ ](fg:crust)\
$line_break\
[╰─](fg:sapphire) 
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'

[directory]
style = "bg:crust sapphire"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#86BBD8 sapphire"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:sapphire sapphire"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#86BBD8 sapphire"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8 sapphire"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:sapphire base"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:sapphire base"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:crust sapphire"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:crust sapphire"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:crust sapphire"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:crust sapphire"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:crust sapphire"
format = '[ $symbol ($version) ]($style)'

[kubernetes]
disabled = true
symbol = "⛵ "
style = "bg:sapphire bold base"
format = '[ $context \($namespace\) ]($style)'

[rust]
symbol = ""
style = "bg:crust sapphire"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:crust sapphire"
format = '[ $time ]($style)'


[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"