# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
#add_newline = true

# Use custom format

#[kubernetes]
#format = 'on [⛵ $context \($namespace\)](dimmed green) '
#disabled = false

format = """
[╭─](fg:#7DCFFF)\
[](bg:#565F89 fg:#7DCFFF)\
$directory\
[](fg:#565F89 bg:#7DCFFF)\
$git_branch\
$git_status\
[](fg:#7DCFFF bg:#565F89)\

$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$rust\
[](fg:#565F89 bg:#7DCFFF)\
$kubernetes\
$docker_context\
[](fg:#7DCFFF bg:#565F89)\
$time(fg:#000)\
[ ](fg:#565F89)\
$line_break\
[╰─](fg:#7DCFFF) 
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'

[directory]
style = "bg:#565F89 black"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#86BBD8 black"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#7DCFFF black"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#86BBD8 black"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8 black"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#7DCFFF black"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#7DCFFF black"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#565F89 black"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#565F89 black"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#565F89 black"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#565F89 black"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#565F89 black"
format = '[ $symbol ($version) ]($style)'

[kubernetes]
disabled = true
symbol = "⛵ "
style = "bg:#7DCFFF bold black"
format = '[ $context \($namespace\) ]($style)'

[rust]
symbol = ""
style = "bg:#565F89 black"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#565F89 black"
format = '[ $time ]($style)'
